<a href="https://colab.research.google.com/github/navap3206-debug/hello-world/blob/main/Bootstrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Carlos Santiago Nava Pulido

In [65]:
from google.colab import files
import pandas as pd
from sklearn.utils import resample
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
dt = files.upload()

Saving Motor Trend Car Road Tests.xlsx to Motor Trend Car Road Tests.xlsx

In [72]:
df = pd.read_excel('Motor Trend Car Road Tests.xlsx')

In [73]:
df.head(1)

       model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

REALIZAR REGRESIÓN LINEAL PREDICIENDO "MPG" Y USANDO HP Y QSEC

In [75]:
Y = ['mpg']
numerical_col = ["hp","qsec"]

In [76]:
X = df[numerical_col]
Y = df[Y]

INTERVALOS DE CONFIANZA

In [77]:
import statsmodels.api as sm
X_sm = sm.add_constant(X)

In [78]:
sm_model = sm.OLS(Y, X_sm)
sm_results = sm_model.fit()

print(sm_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                     25.43
Date:                Mon, 27 Apr 2026   Prob (F-statistic):           4.18e-07
Time:                        23:35:40   Log-Likelihood:                -86.170
No. Observations:                  32   AIC:                             178.3
Df Residuals:                      29   BIC:                             182.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         48.3237     11.103      4.352      0.000      25.615      71.033
hp            -0.0846      0.014     -6.071      0.000      -0.113      -0.056
qsec          -0.8866      0.535     -1.658      0.108      -1.980       0.207
==============================================================================
Omnibus:                        5.102   Durbin-Watson:                   1.355
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                3.987
Skew:                           0.858   Prob(JB):                        0.136
Kurtosis:                       3.220   Cond. No.                     2.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [79]:
#intervalos de confianza proceso
se_b0 = sm_results.bse[0]
se_b1 = sm_results.bse[1]
se_b2 = sm_results.bse[2]

interval_b0 = [sm_results.params[0] - 2 * se_b0, sm_results.params[0] + 2 * se_b0]
interval_b1 = [sm_results.params[1] - 2 * se_b1, sm_results.params[1] + 2 * se_b1]
interval_b2 = [sm_results.params[2] - 2 * se_b2, sm_results.params[2] + 2 * se_b2]

print(interval_b0)
print(interval_b1)
print(interval_b2)

[np.float64(26.117092516520273), np.float64(70.53031782174884)]
[np.float64(-0.11245867264236498), np.float64(-0.05672741470582093)]
[np.float64(-1.955750382680837), np.float64(0.1825911334122834)]

In [80]:
conf_int = sm_results.conf_int(alpha=0.05)
display(conf_int)

               0          1
const  25.614894  71.032516
hp     -0.113089  -0.056097
qsec   -1.979929   0.206770

# BOOTSTRAP

In [81]:
n_iterations = 1000
b0 = []
b1 = []
b2 = []

for i in range(n_iterations):
    boot = resample(df, replace=True, n_samples=len(df))
    X = boot[numerical_col]
    Y = boot[Y.columns]
    X_sm = sm.add_constant(X)
    sm_model = sm.OLS(Y, X_sm)
    sm_results = sm_model.fit()
    b0.append(sm_results.params[0])
    b1.append(sm_results.params[1])
    b2.append(sm_results.params[2])

MEDIAS  Y DESVIACIONES DE CADA BETA

In [82]:
mean_b0 = np.mean(b0)
std_b0 = np.std(b0)
mean_b1 = np.mean(b1)
std_b1 = np.std(b1)
mean_b2 = np.mean(b2)
std_b2 = np.std(b2)

In [83]:
#intervalos
print(mean_b0 - 2 * std_b0, mean_b0 + 2 * std_b0)
print(mean_b1 - 2 * std_b1, mean_b1 + 2 * std_b1)
print(mean_b2 - 2 * std_b2, mean_b2 + 2 * std_b2)

27.282958977031548 72.03305735792591
-0.12232640387531965 -0.053367603638406175
-2.011868337351335 0.12687966368816628

COMPARACIÓN