<a href="https://colab.research.google.com/github/navap3206-debug/hello-world/blob/main/T05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Carlos Santago Nava Pulido
## COmparación de regresiones usando dummies en sus distintas variantes y fomrmas de aborad

In [1]:
from google.colab import files
import statsmodels.api as SM
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [2]:
dt = files.upload()
dt = pd.read_excel('Motor Trend Car Road Tests.xlsx')
dt.head()

Saving Motor Trend Car Road Tests.xlsx to Motor Trend Car Road Tests.xlsx

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
dt = dt.drop(columns='model')
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 2.9 KB

# ***1.1 Realiza una regresión tomando 'mpg' como salida y eliminando la columna 'model'. Considera todos los demás factores como numéricos/ordinales***

## Calcula el R2 e interpreta los signos de los betas.

Escalamos TODO el data frame para este ejercisio

In [4]:
#ESCALADA DE TODO EL DT
dt_all = dt.copy()
scaler = StandardScaler()
X_escalado = scaler.fit_transform(dt_all[['cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb']])
X_escalado_all= pd.DataFrame(X_escalado, columns=['cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb'])
X_escalado_all['vs'] = dt_all['vs'] #LOS CATEGORICOS LOS REINCORPORAMOS
X_escalado_all['am'] = dt_all['am']
vec_y_all = dt['mpg']
print(X_escalado_all.describe())

                cyl          disp         hp          drat            wt  \
count  3.200000e+01  3.200000e+01  32.000000  3.200000e+01  3.200000e+01
mean   2.775558e-17  1.665335e-16   0.000000 -3.053113e-16 -4.718448e-16
std    1.016001e+00  1.016001e+00   1.016001  1.016001e+00  1.016001e+00
min   -1.244457e+00 -1.308518e+00  -1.403130 -1.589643e+00 -1.769642e+00
25%   -1.244457e+00 -9.008917e-01  -0.743705 -9.815764e-01 -6.604034e-01
50%   -1.066677e-01 -2.821771e-01  -0.351014  1.870518e-01  1.118844e-01
75%    1.031121e+00  7.810529e-01   0.493642  6.145986e-01  4.078199e-01
max    1.031121e+00  1.977904e+00   2.790515  2.533809e+00  2.291423e+00

               qsec          gear          carb         vs         am
count  3.200000e+01  3.200000e+01  3.200000e+01  32.000000  32.000000
mean  -1.471046e-15 -2.775558e-17 -2.775558e-17   0.437500   0.406250
std    1.016001e+00  1.016001e+00  1.016001e+00   0.504016   0.498991
min   -1.903996e+00 -9.467293e-01 -1.140108e+00   0.000000   0.000000
25%   -5.436944e-01 -9.467293e-01 -5.110827e-01   0.000000   0.000000
50%   -7.888899e-02  4.303315e-01 -5.110827e-01   0.000000   0.000000
75%    5.977084e-01  4.303315e-01  7.469671e-01   1.000000   1.000000
max    2.871986e+00  1.807392e+00  3.263067e+00   1.000000   1.000000

In [5]:
X_escalado_all

,cyl,disp,hp,drat,wt,qsec,gear,carb,vs,am
0,-0.106668,-0.579750,-0.543655,0.576594,-0.620167,-0.789601,0.430331,0.746967,0,1
1,-0.106668,-0.579750,-0.543655,0.576594,-0.355382,-0.471202,0.430331,0.746967,0,1
2,-1.244457,-1.006026,-0.795570,0.481584,-0.931678,0.432823,0.430331,-1.140108,1,1
3,-0.106668,0.223615,-0.543655,-0.981576,-0.002336,0.904736,-0.946729,-1.140108,1,0
4,1.031121,1.059772,0.419550,-0.848562,0.231297,-0.471202,-0.946729,-0.511083,0,0
5,-0.106668,-0.046906,-0.617748,-1.589643,0.252064,1.348220,-0.946729,-1.140108,1,0
6,1.031121,1.059772,1.456847,-0.734549,0.366285,-1.142114,-0.946729,0.746967,0,0
7,-1.244457,-0.688779,-1.254944,0.177551,-0.028296,1.223135,0.430331,-0.511083,1,0
8,-1.244457,-0.737144,-0.765933,0.614599,-0.069830,2.871986,0.430331,-0.511083,1,0
9,-0.106668,-0.517448,-0.351014,0.614599,0.231297,0.256567,0.430331,0.746967,1,0
10,-0.106668,-0.517448,-0.351014,0.614599,0.231297,0.597708,0.430331,0.746967,1,0
11,1.031121,0.369533,0.493642,-1.000578,0.885470,-0.255145,-0.946729,0.117942,0,0
12,1.031121,0.369533,0.493642,-1.000578,0.532424,-0.141432,-0.946729,0.117942,0,0
13,1.031121,0.369533,0.493642,-1.000578,0.584343,0.085996,-0.946729,0.117942,0,0
14,1.031121,1.977904,0.864106,-1.266608,2.110747,0.074625,-0.946729,0.746967,0,0
15,1.031121,1.879533,1.012291,-1.133593,2.291423,-0.016346,-0.946729,0.746967,0,0
16,1.031121,1.715580,1.234569,-0.696545,2.209392,-0.243774,-0.946729,0.746967,0,0
17,-1.244457,-1.246216,-1.195670,0.918632,-1.056282,0.921793,0.430331,-1.140108,1,1
18,-1.244457,-1.270809,-1.403130,2.533809,-1.663729,0.381652,0.430331,-0.511083,1,1
19,-1.244457,-1.308518,-1.210489,1.184661,-1.435287,1.166278,0.430331,-1.140108,1,1
20,-1.244457,-0.906835,-0.736296,0.196553,-0.781114,1.228820,-0.946729,-1.140108,1,0
21,1.031121,0.715472,0.049086,-1.589643,0.314367,-0.556487,-0.946729,-0.511083,0,0
22,1.031121,0.600705,0.049086,-0.848562,0.226105,-0.312002,-0.946729,-0.511083,0,0
23,1.031121,0.977795,1.456847,0.253559,0.646645,-1.386598,-0.946729,0.746967,0,0
24,1.031121,1.387676,0.419550,-0.981576,0.651837,-0.454145,-0.946729,-0.511083,0,0
25,-1.244457,-1.243757,-1.195670,0.918632,-1.331450,0.597708,0.430331,-1.140108,1,1
26,-1.244457,-0.905195,-0.825207,1.583705,-1.118584,-0.653144,1.807392,-0.511083,0,1
27,-1.244457,-1.111775,-0.499199,0.329567,-1.769642,-0.539430,1.807392,-0.511083,1,1
28,1.031121,0.985993,1.738399,1.184661,-0.049063,-1.903996,1.807392,0.746967,0,1
29,-0.106668,-0.702714,0.419550,0.044536,-0.464411,-1.335427,1.807392,2.005017,0,1
30,1.031121,0.576113,2.790515,-0.107481,0.366285,-1.847139,1.807392,3.263067,0,1
31,-1.244457,-0.899457,-0.558473,0.975638,-0.454027,0.427138,0.430331,-0.511083,1,1

Realizamos la regresion de TODO EL dataframe para conseguir R squared y coeficiented

In [7]:
#REGRESIÓN Y R2
import statsmodels.api as SM
X2 = SM.add_constant(X_escalado_all) #CONCADENAR
model = SM.OLS(vec_y_all,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results1 = model.fit() #OPTIMIZA
print(results1.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.869
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     13.93
Date:                Thu, 19 Feb 2026   Prob (F-statistic):           3.79e-07
Time:                        23:41:07   Log-Likelihood:                -69.855
No. Observations:                  32   AIC:                             161.7
Df Residuals:                      21   BIC:                             177.8
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         18.9278      1.445     13.099      0.000      15.923      21.933
cyl           -0.1959      1.837     -0.107      0.916      -4.016       3.624
disp           1.6267      2.178      0.747      0.463      -2.903       6.157
hp            -1.4497      1.469     -0.987      0.335      -4.505       1.605
drat           0.4142      0.861      0.481      0.635      -1.376       2.204
wt            -3.5780      1.824     -1.961      0.063      -7.372       0.216
qsec           1.4440      1.285      1.123      0.274      -1.229       4.117
gear           0.4760      1.084      0.439      0.665      -1.779       2.731
carb          -0.3170      1.318     -0.241      0.812      -3.057       2.423
vs             0.3178      2.105      0.151      0.881      -4.059       4.694
am             2.5202      2.057      1.225      0.234      -1.757       6.797
==============================================================================
Omnibus:                        1.907   Durbin-Watson:                   1.861
Prob(Omnibus):                  0.385   Jarque-Bera (JB):                1.747
Skew:                           0.521   Prob(JB):                        0.418
Kurtosis:                       2.526   Cond. No.                         14.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Como tal el signo nos habla de la relación de la variable al predecir Y, osea perjudican el rendimiento en mpg

## Realiza un train-test-split donde se use el 40% de los datos para entrenar. Calcula el R2 de entrenamiento y de prueba.

In [8]:
# División 40% entrenamiento / 60% prueba
X_train, X_test, y_train, y_test = train_test_split(dt[['cyl','disp', 'hp', 'drat','wt', 'qsec', 'vs', 'am', 'gear', 'carb']], dt['mpg'], train_size=0.4, random_state=42)
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 21 to 6
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cyl     12 non-null     int64
 1   disp    12 non-null     float64
 2   hp      12 non-null     int64
 3   drat    12 non-null     float64
 4   wt      12 non-null     float64
 5   qsec    12 non-null     float64
 6   vs      12 non-null     int64
 7   am      12 non-null     int64
 8   gear    12 non-null     int64
 9   carb    12 non-null     int64
dtypes: float64(4), int64(6)
memory usage: 1.0 KB

In [9]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 12 entries, 21 to 6
Series name: mpg
Non-Null Count  Dtype
--------------  -----
12 non-null     float64
dtypes: float64(1)
memory usage: 192.0 bytes

escalamos los elementos de train y test por separado

In [10]:
#ESCALADA entrenamiento
scaler = StandardScaler()
X_escalado_train = scaler.fit_transform(X_train[['cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb']])
X_escalado_train= pd.DataFrame(X_escalado_train, columns=[ 'cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb'],index= X_train.index) #SI no pongo el indice original llena con Nan
X_escalado_train['vs'] = X_train['vs'] #REICORPORAMOS CATEGORICOS
X_escalado_train['am'] = X_train['am']
print(X_escalado_train.describe())

#ESCALADA DE PRUEBA
X_escalado_test = scaler.fit_transform(X_test[['cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb']])
X_escalado_test= pd.DataFrame(X_escalado_test, columns=['cyl','disp', 'hp', 'drat','wt', 'qsec', 'gear', 'carb'],index= X_test.index)
X_escalado_test['vs'] = X_test['vs']
X_escalado_test['am'] = X_test['am']
print(X_escalado_test.describe())

                cyl          disp            hp          drat            wt  \
count  1.200000e+01  1.200000e+01  1.200000e+01  1.200000e+01  1.200000e+01
mean   1.850372e-16  5.551115e-17  5.551115e-17  2.498002e-16 -1.942890e-16
std    1.044466e+00  1.044466e+00  1.044466e+00  1.044466e+00  1.044466e+00
min   -9.610745e-01 -1.119839e+00 -1.256644e+00 -1.601287e+00 -1.473656e+00
25%   -9.610745e-01 -7.913969e-01 -7.047645e-01 -8.738093e-01 -6.765925e-01
50%   -4.368520e-01 -4.587298e-01 -2.722106e-01  2.926634e-02  1.987224e-01
75%    1.135815e+00  8.404391e-01  4.101804e-01  7.023921e-01  4.796257e-01
max    1.135815e+00  1.960214e+00  1.905474e+00  2.027739e+00  2.275401e+00

               qsec          gear          carb         vs         am
count  1.200000e+01  1.200000e+01  1.200000e+01  12.000000  12.000000
mean   1.073216e-15 -1.850372e-17  3.700743e-17   0.583333   0.416667
std    1.044466e+00  1.044466e+00  1.044466e+00   0.514929   0.514929
min   -2.078145e+00 -1.039230e+00 -1.341641e+00   0.000000   0.000000
25%   -6.342064e-01 -1.039230e+00 -4.472136e-01   0.000000   0.000000
50%    1.850816e-01  3.464102e-01 -4.472136e-01   1.000000   0.000000
75%    7.282560e-01  3.464102e-01  1.341641e+00   1.000000   1.000000
max    1.247289e+00  1.732051e+00  1.341641e+00   1.000000   1.000000
                cyl          disp            hp          drat            wt  \
count  2.000000e+01  2.000000e+01  2.000000e+01  2.000000e+01  2.000000e+01
mean  -2.026157e-16 -2.040035e-16  1.887379e-16 -1.443290e-16  9.853229e-17
std    1.025978e+00  1.025978e+00  1.025978e+00  1.025978e+00  1.025978e+00
min   -1.477098e+00 -1.382050e+00 -1.298362e+00 -1.649435e+00 -1.558106e+00
25%   -5.539117e-01 -8.196277e-01 -7.533336e-01 -9.639695e-01 -6.851636e-01
50%   -2.461830e-01  2.120396e-02 -5.898251e-02  1.209010e-01  8.926447e-02
75%    9.847319e-01  6.396526e-01  4.039182e-01  8.225585e-01  4.778468e-01
max    9.847319e-01  1.904563e+00  2.718422e+00  1.956005e+00  2.260947e+00

               qsec          gear       carb        vs         am
count  2.000000e+01  2.000000e+01  20.000000  20.00000  20.000000
mean   1.010303e-15  1.498801e-16   0.000000   0.35000   0.400000
std    1.025978e+00  1.025978e+00   1.025978   0.48936   0.502625
min   -1.758851e+00 -8.949569e-01  -1.118034   0.00000   0.000000
25%   -4.694677e-01 -8.949569e-01  -0.698771   0.00000   0.000000
50%   -1.553872e-01 -2.065285e-01   0.000000   0.00000   0.000000
75%    4.906819e-01  4.818999e-01   0.559017   1.00000   1.000000
max    2.814602e+00  1.858757e+00   2.795085   1.00000   1.000000

In [11]:
X_escalado_train = X_escalado_train.reset_index(drop=True) #TENEMOS UN DESMADRE EN LOS INIcES ASÍ QUE RESETEAMOS LOS INDICES
X_escalado_test = X_escalado_test.reset_index(drop=True)
X_escalado_train

,cyl,disp,hp,drat,wt,qsec,gear,carb,vs,am
0,1.135815,0.777056,0.205090,-1.601287,0.539819,-0.647786,-1.039230,-0.447214,0,0
1,-0.961074,-0.935450,-0.346789,0.087799,-1.473656,-0.629680,1.732051,-0.447214,1,1
2,1.135815,0.669496,0.205090,-0.949066,0.454545,-0.388269,-1.039230,-0.447214,0,0
3,-0.961074,-1.084497,-1.256644,2.027739,-1.371327,0.348034,0.346410,-0.447214,1,1
4,-0.961074,-0.736465,-0.406451,0.656402,-0.202568,0.396316,0.346410,-0.447214,1,1
5,-0.961074,-0.743379,-0.585439,-0.029266,-0.518584,1.247289,-1.039230,-1.341641,1,0
6,-0.961074,-0.539016,-1.107487,-0.045990,0.208755,1.241254,0.346410,-0.447214,1,0
7,0.087370,-0.378444,-0.197632,0.338653,0.459561,0.577374,0.346410,1.341641,1,0
8,1.135815,1.960214,1.025451,-1.316985,2.275401,0.022129,-1.039230,1.341641,0,0
9,1.135815,1.030589,1.905474,0.840362,0.188690,-2.078145,1.732051,1.341641,0,1
10,-0.961074,-1.119839,-1.062740,0.840362,-1.150617,1.180901,0.346410,-1.341641,1,1
11,1.135815,1.099735,1.622077,-0.848724,0.589981,-1.269419,-1.039230,1.341641,0,0

ENTRENAMOMS CON LA PARTE TRAIN DE DT

In [12]:
X2 = SM.add_constant(X_escalado_train)
model = SM.OLS(y_train.reset_index(drop=True), X2)
results2 = model.fit()
print(results2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.980
Method:                 Least Squares   F-statistic:                     55.84
Date:                Thu, 19 Feb 2026   Prob (F-statistic):              0.104
Time:                        23:42:15   Log-Likelihood:                -2.6714
No. Observations:                  12   AIC:                             27.34
Df Residuals:                       1   BIC:                             32.68
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         34.4154      5.124      6.717      0.094     -30.689      99.520
cyl           -5.8352      2.260     -2.582      0.235     -34.553      22.883
disp          -1.6489      3.716     -0.444      0.734     -48.861      45.563
hp            -2.1647      1.077     -2.011      0.294     -15.844      11.514
drat          -3.6063      0.869     -4.150      0.151     -14.649       7.436
wt           -10.1594      1.627     -6.244      0.101     -30.834      10.515
qsec           9.1727      1.648      5.566      0.113     -11.769      30.114
gear           2.4806      0.707      3.510      0.177      -6.499      11.460
carb           6.6514      1.499      4.438      0.141     -12.390      25.693
vs           -26.3463      8.698     -3.029      0.203    -136.861      84.168
am             4.4880      1.547      2.901      0.211     -15.171      24.147
==============================================================================
Omnibus:                        4.750   Durbin-Watson:                   1.590
Prob(Omnibus):                  0.093   Jarque-Bera (JB):                1.604
Skew:                          -0.411   Prob(JB):                        0.449
Kurtosis:                       4.591   Cond. No.                         83.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Comprobamos r-squared de test

In [13]:
X2_test = SM.add_constant(X_escalado_test)
X_test_predicr = results2.predict(X2_test)
r2_score(y_test, X_test_predicr)

-7.535229489641667

## Añade regularización L2 con un hiperparámetro lambda decidido por ti. Cambia este valor y compara con varios distintos los R2 de entrenamiento y de prueba.

In [14]:
ridge = Ridge(alpha=1)
ridge.fit(X_escalado_train, y_train)
y_train_pred = ridge.predict(X_escalado_train)
print(f'Resultados RIDGE(L2) -> intercepto: {ridge.intercept_}, coeficientes: {ridge.coef_}')
print(f' R-SQUARED3 {r2_score(y_train, y_train_pred)}')

Resultados RIDGE(L2) -> intercepto: 20.45354467028136, coeficientes: [-0.81001704  0.05078837 -1.60777052  0.0031801  -3.13891231  0.90497654
  1.12945697 -0.41381798 -0.34194537  1.59021631]
 R-SQUARED3 0.9224271673452501

In [15]:
x_test_predicha = ridge.predict(X_escalado_test)
r2_score(y_test, x_test_predicha)

0.5848442641982937

# ***REPETIMOS EL PROCEDIMIENTO PERO USANDO "QSEC" COMO VARIABLE A PREDECIR***

In [16]:
#ESCALADA DE TODO EL DT PERO CAMBIANDO LAS VARIABLES
dt_all = dt.copy()
scaler = StandardScaler()
X_escalado_2 = scaler.fit_transform(dt_all[['mpg','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb']])
X_escalado_all_2= pd.DataFrame(X_escalado, columns=['mph','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb'])
X_escalado_all_2['vs'] = dt_all['vs'] #LOS CATEGORICOS LOS REINCORPORAMOS
X_escalado_all_2['am'] = dt_all['am']
vec_y_all_2 = dt['qsec']
X_escalado_all_2.head()

,mph,cyl,disp,hp,drat,wt,gear,carb,vs,am
0,-0.106668,-0.579750,-0.543655,0.576594,-0.620167,-0.789601,0.430331,0.746967,0,1
1,-0.106668,-0.579750,-0.543655,0.576594,-0.355382,-0.471202,0.430331,0.746967,0,1
2,-1.244457,-1.006026,-0.795570,0.481584,-0.931678,0.432823,0.430331,-1.140108,1,1
3,-0.106668,0.223615,-0.543655,-0.981576,-0.002336,0.904736,-0.946729,-1.140108,1,0
4,1.031121,1.059772,0.419550,-0.848562,0.231297,-0.471202,-0.946729,-0.511083,0,0

In [17]:
#Regresión del datafram completo
X2 = SM.add_constant(X_escalado_all_2) #CONCADENAR
model = SM.OLS(vec_y_all_2,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results4 = model.fit() #OPTIMIZA
print(results4.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                   qsec   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.702e+28
Date:                Thu, 19 Feb 2026   Prob (F-statistic):          5.99e-297
Time:                        23:44:05   Log-Likelihood:                 986.65
No. Observations:                  32   AIC:                            -1951.
Df Residuals:                      21   BIC:                            -1935.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         17.8488   6.63e-15   2.69e+15      0.000      17.849      17.849
mph        -7.994e-15   8.42e-15     -0.949      0.353   -2.55e-14    9.52e-15
cyl         7.105e-15   9.99e-15      0.711      0.485   -1.37e-14    2.79e-14
disp       -1.332e-15   6.74e-15     -0.198      0.845   -1.53e-14    1.27e-14
hp          6.217e-15   3.95e-15      1.575      0.130   -1.99e-15    1.44e-14
drat        1.776e-15   8.37e-15      0.212      0.834   -1.56e-14    1.92e-14
wt             1.7588   5.89e-15   2.98e+14      0.000       1.759       1.759
gear       -8.549e-15   4.97e-15     -1.719      0.100   -1.89e-14    1.79e-15
carb       -3.109e-15   6.04e-15     -0.515      0.612   -1.57e-14    9.46e-15
vs         -1.776e-15   9.65e-15     -0.184      0.856   -2.18e-14    1.83e-14
am          1.776e-15   9.43e-15      0.188      0.852   -1.78e-14    2.14e-14
==============================================================================
Omnibus:                       15.330   Durbin-Watson:                   0.889
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               16.641
Skew:                           1.426   Prob(JB):                     0.000243
Kurtosis:                       5.085   Cond. No.                         14.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Realiza un train-test-split donde se use el 40% de los datos para entrenar. Calcula el R2 de entrenamiento y de prueba, ahora con qsec

In [18]:
# División 40% entrenamiento / 60% prueba
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(dt[['mpg','cyl','disp', 'hp', 'drat','wt', 'vs', 'am', 'gear', 'carb']], dt['qsec'], train_size=0.4, random_state=42)
X_train_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 21 to 6
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     12 non-null     float64
 1   cyl     12 non-null     int64
 2   disp    12 non-null     float64
 3   hp      12 non-null     int64
 4   drat    12 non-null     float64
 5   wt      12 non-null     float64
 6   vs      12 non-null     int64
 7   am      12 non-null     int64
 8   gear    12 non-null     int64
 9   carb    12 non-null     int64
dtypes: float64(4), int64(6)
memory usage: 1.0 KB

In [19]:
y_train_2.info() #COmprobamos nuesto vector

<class 'pandas.core.series.Series'>
Index: 12 entries, 21 to 6
Series name: qsec
Non-Null Count  Dtype
--------------  -----
12 non-null     float64
dtypes: float64(1)
memory usage: 192.0 bytes

In [20]:
#Escalamos las varables de entrenamiento y de text X
#ESCALADA entrenamiento
scaler = StandardScaler()
X_escalado_train_2 = scaler.fit_transform(X_train_2[['mpg','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb']])
X_escalado_train_2= pd.DataFrame(X_escalado_train_2, columns=['mpg','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb'], index=X_train_2.index)
X_escalado_train_2['vs'] = X_train_2['vs'] #REICORPORAMOS CATEGORICOS
X_escalado_train_2['am'] = X_train_2['am']
X_escalado_train_2 = X_escalado_train_2.reset_index(drop=True) #No queremos problemas con los indices de la regresión
print(X_escalado_train_2.head())

#ESCALADA DE PRUEBA
X_escalado_test_2 = scaler.fit_transform(X_test_2[['mpg','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb']])
X_escalado_test_2= pd.DataFrame(X_escalado_test_2, columns=['mpg','cyl','disp', 'hp', 'drat','wt', 'gear', 'carb'], index=X_test_2.index)
X_escalado_test_2['vs'] = X_test_2['vs'] #REICORPORAMOS CATEGORICOS
X_escalado_test_2['am'] = X_test_2['am']
X_escalado_test_2 = X_escalado_test_2.reset_index(drop=True)
print(X_escalado_test_2.head())

        mpg       cyl      disp        hp      drat        wt      gear  \
0 -0.757596  1.135815  0.777056  0.205090 -1.601287  0.539819 -1.039230
1  1.326376 -0.961074 -0.935450 -0.346789  0.087799 -1.473656  1.732051
2 -0.799556  1.135815  0.669496  0.205090 -0.949066  0.454545 -1.039230
3  1.326376 -0.961074 -1.084497 -1.256644  2.027739 -1.371327  0.346410
4  0.067601 -0.961074 -0.736465 -0.406451  0.656402 -0.202568  0.346410

       carb  vs  am
0 -0.447214   0   0
1 -0.447214   1   1
2 -0.447214   0   0
3 -0.447214   1   1
4 -0.447214   1   1
        mpg       cyl      disp        hp      drat        wt      gear  \
0  0.021010 -0.246183 -0.810577  0.329257  0.207259 -0.644116  1.858757
1 -1.839903  0.984732  1.904563  0.926548 -1.131288  2.260947 -0.894957
2 -0.079039  0.984732  1.387394  0.329257 -0.958572  0.532577 -0.894957
3  2.562257 -1.477098 -1.382050 -1.298362  1.200374 -1.268037  0.481900
4  0.641315 -1.477098 -0.846779 -0.865326  0.854943 -0.228169  0.481900

       carb  vs  am
0  1.677051   0   1
1  0.559017   0   0
2 -0.559017   0   0
3 -1.118034   1   1
4 -0.559017   1   0

In [21]:
#compruebo mi vector Y
vec_y_all_2.head()

0    16.46
1    17.02
2    18.61
3    19.44
4    17.02
Name: qsec, dtype: float64

ENTRENAMOS MODELO PARA QSEC con train

In [22]:
X2 = SM.add_constant(X_escalado_train_2)
model = SM.OLS(y_train_2.reset_index(drop=True), X2)
results5 = model.fit()
print(results5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   qsec   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     94.94
Date:                Thu, 19 Feb 2026   Prob (F-statistic):             0.0797
Time:                        23:44:50   Log-Likelihood:                 18.054
No. Observations:                  12   AIC:                            -14.11
Df Residuals:                       1   BIC:                            -8.775
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         15.4904      0.757     20.469      0.031       5.875      25.106
mpg            1.2511      0.225      5.566      0.113      -1.605       4.107
cyl            1.0422      0.389      2.676      0.228      -3.906       5.990
disp           0.3321      0.642      0.517      0.696      -7.824       8.488
hp             0.3633      0.230      1.581      0.359      -2.556       3.282
drat           0.6463      0.131      4.928      0.127      -1.020       2.313
wt             1.7980      0.337      5.340      0.118      -2.481       6.077
gear          -0.4456      0.108     -4.116      0.152      -1.821       0.930
carb          -1.1947      0.205     -5.820      0.108      -3.803       1.414
vs             4.7734      1.244      3.838      0.162     -11.028      20.575
am            -0.7958      0.281     -2.830      0.216      -4.368       2.777
==============================================================================
Omnibus:                        5.092   Durbin-Watson:                   1.681
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                1.933
Skew:                           0.188   Prob(JB):                        0.380
Kurtosis:                       4.930   Cond. No.                         72.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

COMRPOBAMOS EL MODELO CON TEST

In [23]:
#PREDECIMOS Y CONSEGUIMOS R SQUARED
X2_test = SM.add_constant(X_escalado_test_2)
X_test_predecir_2 = results5.predict(X2_test)
r2_score(y_test_2, X_test_predecir_2)

-0.6473988200504392

AHORA REALIZAMOS L2 CON QSEC COMO VARIABLE A PREDECIR...

In [24]:
ridge2 = Ridge(alpha=1)
ridge2.fit(X_escalado_train_2, y_train_2)
y_train_pred_2 = ridge2.predict(X_escalado_train_2)
print(f'Resultados RIDGE(L2) -> intercepto: {ridge2.intercept_}, coeficientes: {ridge2.coef_}')
print(f' R-SQUARED3 {r2_score(y_train_2, y_train_pred_2)}')

Resultados RIDGE(L2) -> intercepto: 17.811817028654126, coeficientes: [ 0.23031972 -0.58125653 -0.26576547 -0.63213369  0.19475573  0.87678289
 -0.42170365 -0.17136178  0.49178524 -0.37286021]
 R-SQUARED3 0.9428603878814251

In [25]:
x_test_predicha = ridge2.predict(X_escalado_test_2)
r2_score(y_test_2, x_test_predicha)

0.7459509492140477

# ***2.1 Realiza una regresión tomando 'mpg' como salida y eliminando la columna 'model'. Crea columnas dummies para los factores 'cyl', 'gear' y 'carb'.***

In [26]:
#Creamos nuestras X
X = dt.drop(columns=['mpg'])

#Creamos las dummies para las 3 columnas categóricas
X_listo = pd.get_dummies(X, columns=['cyl', 'gear', 'carb'], drop_first=True)

# Convertimos los booleanos (True/False) a números (1/0) para que statsmodels no se queje
X_listo = X_listo.astype(int)

X_listo.head()

,disp,hp,drat,wt,qsec,vs,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,160,110,3,2,16,0,1,1,0,1,0,0,0,1,0,0
1,160,110,3,2,17,0,1,1,0,1,0,0,0,1,0,0
2,108,93,3,2,18,1,1,0,0,1,0,0,0,0,0,0
3,258,110,3,3,19,1,0,1,0,0,0,0,0,0,0,0
4,360,175,3,3,17,0,0,0,1,0,0,1,0,0,0,0

In [27]:
#escalamos los que no transfromamos a dummies
scaler = StandardScaler()
X_escalado_dum = scaler.fit_transform(X_listo[['disp', 'hp', 'drat','wt', 'qsec']])
X_escalado_all_dum= pd.DataFrame(X_escalado_dum, columns=['disp', 'hp', 'drat','wt', 'qsec'])
#VOLVEMOS TODO UN MISO DATAFRAME
X_listo = X_listo.drop(columns=['disp', 'hp', 'drat','wt', 'qsec'])
X_escalado_all_dum = pd.concat([X_escalado_all_dum, X_listo], axis=1)
X_escalado_all_dum.head()

,disp,hp,drat,wt,qsec,vs,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,-0.577460,-0.543655,-0.229416,-0.692532,-0.755550,0,1,1,0,1,0,0,0,1,0,0
1,-0.577460,-0.543655,-0.229416,-0.692532,-0.193280,0,1,1,0,1,0,0,0,1,0,0
2,-1.003389,-0.795570,-0.229416,-0.692532,0.368989,1,1,0,0,1,0,0,0,0,0,0
3,0.225251,-0.543655,-0.229416,0.270991,0.931259,1,0,1,0,0,0,0,0,0,0,0
4,1.060725,0.419550,-0.229416,0.270991,-0.193280,0,0,0,1,0,0,1,0,0,0,0

REALIZAMOS LA REGRESION CON LA NUEVA TABLA

In [28]:
X2 = SM.add_constant(X_escalado_all_dum) #CONCADENAR
model = SM.OLS(vec_y_all,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results_dum = model.fit() #OPTIMIZA
print(results_dum.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.898
Model:                            OLS   Adj. R-squared:                  0.789
Method:                 Least Squares   F-statistic:                     8.225
Date:                Thu, 19 Feb 2026   Prob (F-statistic):           9.20e-05
Time:                        23:46:38   Log-Likelihood:                -65.904
No. Observations:                  32   AIC:                             165.8
Df Residuals:                      15   BIC:                             190.7
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         17.2925      5.472      3.160      0.006       5.629      28.956
disp           2.2353      3.375      0.662      0.518      -4.958       9.429
hp            -5.3055      2.630     -2.017      0.062     -10.911       0.300
drat           1.0703      0.780      1.373      0.190      -0.591       2.732
wt            -2.7005      1.672     -1.615      0.127      -6.264       0.863
qsec           0.6929      1.634      0.424      0.678      -2.789       4.175
vs             2.0296      2.805      0.723      0.481      -3.950       8.009
am             0.6418      3.406      0.188      0.853      -6.618       7.902
cyl_6         -1.8341      2.717     -0.675      0.510      -7.625       3.957
cyl_8          1.8050      7.036      0.257      0.801     -13.191      16.801
gear_4         0.5948      3.843      0.155      0.879      -7.597       8.787
gear_5         4.5826      3.902      1.174      0.259      -3.734      12.899
carb_2        -1.0605      2.253     -0.471      0.645      -5.863       3.742
carb_3         0.8555      3.677      0.233      0.819      -6.982       8.693
carb_4         0.9769      4.033      0.242      0.812      -7.619       9.573
carb_6         2.0969      5.657      0.371      0.716      -9.962      14.156
carb_8         6.4724      7.815      0.828      0.421     -10.185      23.130
==============================================================================
Omnibus:                        0.669   Durbin-Watson:                   2.091
Prob(Omnibus):                  0.716   Jarque-Bera (JB):                0.761
Skew:                           0.249   Prob(JB):                        0.684
Kurtosis:                       2.433   Cond. No.                         44.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## **Realiza un train-test-split donde se use el 40% de los datos para entrenar. Calcula el R2 de entrenamiento y de prueba.**

In [29]:
#Creamos nuestras X  de nuevo
X = dt.drop(columns=['mpg'])
X_listo = pd.get_dummies(X, columns=['cyl', 'gear', 'carb'], drop_first=True)
X_listo = X_listo.astype(int)

X_listo.head()

,disp,hp,drat,wt,qsec,vs,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,160,110,3,2,16,0,1,1,0,1,0,0,0,1,0,0
1,160,110,3,2,17,0,1,1,0,1,0,0,0,1,0,0
2,108,93,3,2,18,1,1,0,0,1,0,0,0,0,0,0
3,258,110,3,3,19,1,0,1,0,0,0,0,0,0,0,0
4,360,175,3,3,17,0,0,0,1,0,0,1,0,0,0,0

In [30]:
X_train_dum, X_test_dum, y_train_dum, y_test_dum = train_test_split(X_listo, dt['mpg'], train_size=0.4, random_state=42)
X_train_dum.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 21 to 6
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   disp    12 non-null     int64
 1   hp      12 non-null     int64
 2   drat    12 non-null     int64
 3   wt      12 non-null     int64
 4   qsec    12 non-null     int64
 5   vs      12 non-null     int64
 6   am      12 non-null     int64
 7   cyl_6   12 non-null     int64
 8   cyl_8   12 non-null     int64
 9   gear_4  12 non-null     int64
 10  gear_5  12 non-null     int64
 11  carb_2  12 non-null     int64
 12  carb_3  12 non-null     int64
 13  carb_4  12 non-null     int64
 14  carb_6  12 non-null     int64
 15  carb_8  12 non-null     int64
dtypes: int64(16)
memory usage: 1.6 KB

In [31]:
y_train_dum.head()

21    15.5
27    30.4
22    15.2
18    30.4
31    21.4
Name: mpg, dtype: float64

In [32]:
#escalamos los que no transfromamos a dummies
scaler = StandardScaler()
X_escalado_dum = scaler.fit_transform(X_train_dum[['disp', 'hp', 'drat','wt', 'qsec']])
X_escalado_train_dum= pd.DataFrame(X_escalado_dum, columns=['disp', 'hp', 'drat','wt', 'qsec'], index = X_train_dum.index)
#VOLVEMOS TODO UN MISMO DATAFRAME
X_train_dum = X_train_dum.drop(columns=['disp', 'hp', 'drat','wt', 'qsec'])
X_escalado_train_dum = pd.concat([X_escalado_train_dum, X_train_dum], axis=1)
X_escalado_train_dum.reset_index(drop=True, inplace=True)
X_escalado_train_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   disp    12 non-null     float64
 1   hp      12 non-null     float64
 2   drat    12 non-null     float64
 3   wt      12 non-null     float64
 4   qsec    12 non-null     float64
 5   vs      12 non-null     int64
 6   am      12 non-null     int64
 7   cyl_6   12 non-null     int64
 8   cyl_8   12 non-null     int64
 9   gear_4  12 non-null     int64
 10  gear_5  12 non-null     int64
 11  carb_2  12 non-null     int64
 12  carb_3  12 non-null     int64
 13  carb_4  12 non-null     int64
 14  carb_6  12 non-null     int64
 15  carb_8  12 non-null     int64
dtypes: float64(5), int64(11)
memory usage: 1.6 KB

HACEMOS POR SEPARADO PARA LAS X DE TEST

In [33]:
#escalamos los que no transformamos a dummies pero ahora de test
scaler = StandardScaler()

numeric_cols = ['disp', 'hp', 'drat','wt', 'qsec']

X_test_numeric_to_scale = X_test_dum[numeric_cols]
X_escalado_dum_test_values = scaler.fit_transform(X_test_numeric_to_scale)
X_escalado_test_dum_numeric = pd.DataFrame(X_escalado_dum_test_values, columns=numeric_cols, index=X_test_dum.index)
dummy_and_categorical_cols = X_test_dum.columns.drop(numeric_cols)
X_test_dummies = X_test_dum[dummy_and_categorical_cols]
X_escalado_test_dum = pd.concat([X_escalado_test_dum_numeric, X_test_dummies], axis=1)
X_escalado_test_dum.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 29 to 3
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   disp    20 non-null     float64
 1   hp      20 non-null     float64
 2   drat    20 non-null     float64
 3   wt      20 non-null     float64
 4   qsec    20 non-null     float64
 5   vs      20 non-null     int64
 6   am      20 non-null     int64
 7   cyl_6   20 non-null     int64
 8   cyl_8   20 non-null     int64
 9   gear_4  20 non-null     int64
 10  gear_5  20 non-null     int64
 11  carb_2  20 non-null     int64
 12  carb_3  20 non-null     int64
 13  carb_4  20 non-null     int64
 14  carb_6  20 non-null     int64
 15  carb_8  20 non-null     int64
dtypes: float64(5), int64(11)
memory usage: 2.7 KB

In [34]:
y_test_dum.info()

<class 'pandas.core.series.Series'>
Index: 20 entries, 29 to 3
Series name: mpg
Non-Null Count  Dtype
--------------  -----
20 non-null     float64
dtypes: float64(1)
memory usage: 320.0 bytes

REALZAMOS LA REGRESIÓN EN CUESTIO CON TRAIN

In [35]:
X2 = SM.add_constant(X_escalado_train_dum) #CONCADENAR
model = SM.OLS(y_train_dum.reset_index(drop=True),X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results_dum = model.fit() #OPTIMIZA
print(results_dum.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Thu, 19 Feb 2026   Prob (F-statistic):                nan
Time:                        23:47:18   Log-Likelihood:                 350.66
No. Observations:                  12   AIC:                            -677.3
Df Residuals:                       0   BIC:                            -671.5
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3021        inf         -0        nan         nan         nan
disp          32.4393        inf          0        nan         nan         nan
hp            11.6164        inf          0        nan         nan         nan
drat          -6.7419        inf         -0        nan         nan         nan
wt           -33.9083        inf         -0        nan         nan         nan
qsec          23.3293        inf          0        nan         nan         nan
vs             1.2128        inf          0        nan         nan         nan
am             0.5558        inf          0        nan         nan         nan
cyl_6          8.9048        inf          0        nan         nan         nan
cyl_8         -1.5149        inf         -0        nan         nan         nan
gear_4        22.0668        inf          0        nan         nan         nan
gear_5        22.7001        inf          0        nan         nan         nan
carb_2        10.7530        inf          0        nan         nan         nan
carb_3              0        nan        nan        nan         nan         nan
carb_4         5.4435        inf          0        nan         nan         nan
carb_6              0        nan        nan        nan         nan         nan
carb_8              0        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                        0.272   Durbin-Watson:                   1.916
Prob(Omnibus):                  0.873   Jarque-Bera (JB):                0.425
Skew:                          -0.079   Prob(JB):                        0.808
Kurtosis:                       2.091   Cond. No.                         183.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1795: RuntimeWarning: divide by zero encountered in divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1795: RuntimeWarning: invalid value encountered in scalar multiply
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1717: RuntimeWarning: divide by zero encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1527: RuntimeWarning: invalid value encountered in multiply
  cov_p = self.normalized_cov_params * scale

comrpobamos r2 de test

In [36]:
dum_test = SM.add_constant(X_escalado_test_dum)
X_test_dum_predict = results_dum.predict(dum_test)
r2_score(y_test_dum, X_test_dum_predict)

-16.438770829234354

AHORA HACEMOS PRUEBA RIDGE

In [59]:
ridge3 = Ridge(alpha=100)
ridge3.fit(X_escalado_train_dum, y_train_dum)
y_train_pred_3 = ridge3.predict(X_escalado_train_dum)
print(f'Resultados RIDGE(L2) -> intercepto: {ridge3.intercept_}, coeficientes: {ridge3.coef_}')
print(f' R-SQUARED3 {r2_score(y_train_dum, y_train_pred_3)}')

Resultados RIDGE(L2) -> intercepto: 20.7468330577957, coeficientes: [-0.51565963 -0.44390703  0.33034443 -0.54641876  0.2305606   0.22189814
  0.20392579 -0.03159572 -0.22189814  0.14821427  0.04829763  0.07555725
  0.         -0.17120908  0.          0.        ]
 R-SQUARED3 0.4529079145445388

In [60]:

x_test_predicha_dum = ridge3.predict(X_test_dum)
r2_score(y_test_dum, x_test_predicha_dum)

-1652.0171525149117

## AHORA TODO PERO CON VARIABLE DE SALIDA DE QSEC

In [40]:
#Creamos nuestras X
X = dt.drop(columns=['qsec'])

#Creamos las dummies para las 3 columnas categóricas
X_listo = pd.get_dummies(X, columns=['cyl', 'gear', 'carb'], drop_first=True)

# Convertimos los booleanos (True/False) a números (1/0) para que statsmodels no se queje
X_listo = X_listo.astype(int)

X_listo.head()

,mpg,disp,hp,drat,wt,vs,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,21,160,110,3,2,0,1,1,0,1,0,0,0,1,0,0
1,21,160,110,3,2,0,1,1,0,1,0,0,0,1,0,0
2,22,108,93,3,2,1,1,0,0,1,0,0,0,0,0,0
3,21,258,110,3,3,1,0,1,0,0,0,0,0,0,0,0
4,18,360,175,3,3,0,0,0,1,0,0,1,0,0,0,0

In [41]:
#escalamos los que no transfromamos a dummies
scaler = StandardScaler()
X_escalado_dum_2 = scaler.fit_transform(X_listo[['mpg','disp', 'hp', 'drat','wt']])
X_escalado_all_dum_2= pd.DataFrame(X_escalado_dum_2, columns=['mpg' , 'disp', 'hp', 'drat','wt'])
#VOLVEMOS TODO UN MISO DATAFRAME
X_listo_2 = X_listo.drop(columns=['mpg','disp', 'hp', 'drat','wt'])
X_escalado_all_dum_2 = pd.concat([X_escalado_all_dum_2, X_listo], axis=1)
X_escalado_all_dum_2.head()

,mpg,disp,hp,drat,wt,mpg,disp,hp,drat,wt,...,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,0.222362,-0.577460,-0.543655,-0.229416,-0.692532,21,160,110,3,2,...,1,1,0,1,0,0,0,1,0,0
1,0.222362,-0.577460,-0.543655,-0.229416,-0.692532,21,160,110,3,2,...,1,1,0,1,0,0,0,1,0,0
2,0.391781,-1.003389,-0.795570,-0.229416,-0.692532,22,108,93,3,2,...,1,0,0,1,0,0,0,0,0,0
3,0.222362,0.225251,-0.543655,-0.229416,0.270991,21,258,110,3,3,...,0,1,0,0,0,0,0,0,0,0
4,-0.285894,1.060725,0.419550,-0.229416,0.270991,18,360,175,3,3,...,0,0,1,0,0,1,0,0,0,0

REALIZAMO A REGRESIÓN CON TABLA COMPLETA

In [42]:
X2 = SM.add_constant(X_escalado_all_dum_2) #CONCADENAR
model = SM.OLS(vec_y_all_2,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results_dum_qsec = model.fit() #OPTIMIZA
print(results_dum_qsec.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                   qsec   R-squared:                       0.906
Model:                            OLS   Adj. R-squared:                  0.805
Method:                 Least Squares   F-statistic:                     9.014
Date:                Thu, 19 Feb 2026   Prob (F-statistic):           5.23e-05
Time:                        23:49:28   Log-Likelihood:                -25.679
No. Observations:                  32   AIC:                             85.36
Df Residuals:                      15   BIC:                             110.3
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5881      0.078      7.513      0.000       0.421       0.755
mpg           -1.9037      0.264     -7.213      0.000      -2.466      -1.341
disp          -1.1103      0.148     -7.513      0.000      -1.425      -0.795
hp            -1.2782      0.170     -7.508      0.000      -1.641      -0.915
drat          -0.8233      0.185     -4.447      0.000      -1.218      -0.429
wt            -0.5926      0.291     -2.036      0.060      -1.213       0.028
mpg            0.3423      0.044      7.711      0.000       0.248       0.437
disp           0.0156      0.008      1.984      0.066      -0.001       0.032
hp             0.0167      0.011      1.478      0.160      -0.007       0.041
drat           1.3893      0.234      5.930      0.000       0.890       1.889
wt             0.9839      0.246      3.995      0.001       0.459       1.509
vs             0.3124      0.808      0.387      0.704      -1.410       2.034
am            -1.6341      0.833     -1.962      0.069      -3.410       0.141
cyl_6         -1.3387      0.736     -1.819      0.089      -2.907       0.230
cyl_8         -3.3483      1.746     -1.918      0.074      -7.069       0.372
gear_4         1.4366      1.028      1.398      0.183      -0.754       3.628
gear_5        -0.0819      1.149     -0.071      0.944      -2.530       2.366
carb_2        -0.7577      0.615     -1.232      0.237      -2.069       0.553
carb_3         0.2028      1.050      0.193      0.849      -2.035       2.440
carb_4        -1.6620      1.017     -1.634      0.123      -3.830       0.506
carb_6        -0.9264      1.575     -0.588      0.565      -4.284       2.431
carb_8        -0.8140      2.280     -0.357      0.726      -5.675       4.047
==============================================================================
Omnibus:                        9.460   Durbin-Watson:                   2.642
Prob(Omnibus):                  0.009   Jarque-Bera (JB):               11.324
Skew:                           0.690   Prob(JB):                      0.00348
Kurtosis:                       5.567   Cond. No.                     5.90e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.52e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

HACEMOS EL SPLIT NECESARIO DEL 40

In [43]:
#Creamos nuestras X  de nuevo a dummies
X = dt.drop(columns=['qsec'])
X_listo = pd.get_dummies(X, columns=['cyl', 'gear', 'carb'], drop_first=True)
X_listo = X_listo.astype(int)

X_listo.head()

,mpg,disp,hp,drat,wt,vs,am,cyl_6,cyl_8,gear_4,gear_5,carb_2,carb_3,carb_4,carb_6,carb_8
0,21,160,110,3,2,0,1,1,0,1,0,0,0,1,0,0
1,21,160,110,3,2,0,1,1,0,1,0,0,0,1,0,0
2,22,108,93,3,2,1,1,0,0,1,0,0,0,0,0,0
3,21,258,110,3,3,1,0,1,0,0,0,0,0,0,0,0
4,18,360,175,3,3,0,0,0,1,0,0,1,0,0,0,0

In [44]:
X_train_dum_q, X_test_dum_q, y_train_dum_q, y_test_dum_q = train_test_split(X_listo, dt['qsec'], train_size=0.4, random_state=42)
X_train_dum_q.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 21 to 6
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     12 non-null     int64
 1   disp    12 non-null     int64
 2   hp      12 non-null     int64
 3   drat    12 non-null     int64
 4   wt      12 non-null     int64
 5   vs      12 non-null     int64
 6   am      12 non-null     int64
 7   cyl_6   12 non-null     int64
 8   cyl_8   12 non-null     int64
 9   gear_4  12 non-null     int64
 10  gear_5  12 non-null     int64
 11  carb_2  12 non-null     int64
 12  carb_3  12 non-null     int64
 13  carb_4  12 non-null     int64
 14  carb_6  12 non-null     int64
 15  carb_8  12 non-null     int64
dtypes: int64(16)
memory usage: 1.6 KB

In [45]:

#escalamos los que no transfromamos a dummies
scaler = StandardScaler()
X_escalado_dum_qsec = scaler.fit_transform(X_train_dum_q[['mpg','disp', 'hp', 'drat','wt']])
X_escalado_train_dum_qsec= pd.DataFrame(X_escalado_dum_qsec, columns=['mpg','disp', 'hp', 'drat','wt'], index = X_train_dum_q.index)
#VOLVEMOS TODO UN MISMO DATAFRAME
X_train_dum_q = X_train_dum_q.drop(columns=['mpg','disp', 'hp', 'drat','wt'])
X_escalado_train_dum_qsec = pd.concat([X_escalado_train_dum_qsec, X_train_dum_q], axis=1)
X_escalado_train_dum_qsec.reset_index(drop=True, inplace=True)
X_escalado_train_dum_qsec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     12 non-null     float64
 1   disp    12 non-null     float64
 2   hp      12 non-null     float64
 3   drat    12 non-null     float64
 4   wt      12 non-null     float64
 5   vs      12 non-null     int64
 6   am      12 non-null     int64
 7   cyl_6   12 non-null     int64
 8   cyl_8   12 non-null     int64
 9   gear_4  12 non-null     int64
 10  gear_5  12 non-null     int64
 11  carb_2  12 non-null     int64
 12  carb_3  12 non-null     int64
 13  carb_4  12 non-null     int64
 14  carb_6  12 non-null     int64
 15  carb_8  12 non-null     int64
dtypes: float64(5), int64(11)
memory usage: 1.6 KB

In [46]:
#escalamos los que no transformamos a dummies pero ahora de test
scaler = StandardScaler()

numeric_cols = ['mpg','disp', 'hp', 'drat','wt']

X_test_numeric_to_scale_qsec = X_test_dum_q[numeric_cols]
X_escalado_dum_test_values = scaler.fit_transform(X_test_numeric_to_scale_qsec)
X_escalado_test_dum_numeric = pd.DataFrame(X_escalado_dum_test_values, columns=numeric_cols, index=X_test_dum_q.index)
dummy_and_categorical_cols = X_test_dum_q.columns.drop(numeric_cols)
X_test_dummies_q = X_test_dum_q[dummy_and_categorical_cols]
X_escalado_test_dum_qsec = pd.concat([X_escalado_test_dum_numeric, X_test_dummies_q], axis=1)
X_escalado_test_dum_qsec.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 29 to 3
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     20 non-null     float64
 1   disp    20 non-null     float64
 2   hp      20 non-null     float64
 3   drat    20 non-null     float64
 4   wt      20 non-null     float64
 5   vs      20 non-null     int64
 6   am      20 non-null     int64
 7   cyl_6   20 non-null     int64
 8   cyl_8   20 non-null     int64
 9   gear_4  20 non-null     int64
 10  gear_5  20 non-null     int64
 11  carb_2  20 non-null     int64
 12  carb_3  20 non-null     int64
 13  carb_4  20 non-null     int64
 14  carb_6  20 non-null     int64
 15  carb_8  20 non-null     int64
dtypes: float64(5), int64(11)
memory usage: 2.7 KB

REGRESION DEL 40% de qsec

In [69]:
X2 = SM.add_constant(X_escalado_train_dum_qsec) #CONCADENAR
model = SM.OLS(y_train_dum_q.reset_index(drop=True),X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results_dum_qsec_2 = model.fit() #OPTIMIZA
print(results_dum_qsec_2.summary())#RESUME

                            OLS Regression Results
==============================================================================
Dep. Variable:                   qsec   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Fri, 20 Feb 2026   Prob (F-statistic):                nan
Time:                        00:18:55   Log-Likelihood:                 360.26
No. Observations:                  12   AIC:                            -696.5
Df Residuals:                       0   BIC:                            -690.7
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0090        inf          0        nan         nan         nan
mpg            1.0642        inf          0        nan         nan         nan
disp          -0.3942        inf         -0        nan         nan         nan
hp            -0.1436        inf         -0        nan         nan         nan
drat           0.2664        inf          0        nan         nan         nan
wt             1.8897        inf          0        nan         nan         nan
vs             7.4468        inf          0        nan         nan         nan
am             0.3772        inf          0        nan         nan         nan
cyl_6          1.0806        inf          0        nan         nan         nan
cyl_8          5.5622        inf          0        nan         nan         nan
gear_4        -1.2001        inf         -0        nan         nan         nan
gear_5        -2.2413        inf         -0        nan         nan         nan
carb_2        -0.9461        inf         -0        nan         nan         nan
carb_3              0        nan        nan        nan         nan         nan
carb_4        -1.8833        inf         -0        nan         nan         nan
carb_6              0        nan        nan        nan         nan         nan
carb_8              0        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                        2.936   Durbin-Watson:                   1.552
Prob(Omnibus):                  0.230   Jarque-Bera (JB):                1.174
Skew:                           0.759   Prob(JB):                        0.556
Kurtosis:                       3.214   Cond. No.                         58.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1795: RuntimeWarning: divide by zero encountered in divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1795: RuntimeWarning: invalid value encountered in scalar multiply
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1717: RuntimeWarning: divide by zero encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1527: RuntimeWarning: invalid value encountered in multiply
  cov_p = self.normalized_cov_params * scale

VUELVE A SOBREAJUSTAR DE FORMA RADICAL

In [70]:
#continuamos con test
dum_test = SM.add_constant(X_escalado_test_dum_qsec)
X_test_dum_predict = results_dum_qsec_2.predict(dum_test)
r2_score(y_test_dum_q, X_test_dum_predict)

-1.599345376544751

APLICAMOS RIDGE a qsec

In [67]:
ridge4 = Ridge(alpha=.1)
ridge4.fit(X_escalado_train_dum_qsec, y_train_dum_q)
y_train_pred_4 = ridge4.predict(X_escalado_train_dum_qsec)
print(f'Resultados RIDGE(L2) -> intercepto: {ridge3.intercept_}, coeficientes: {ridge4.coef_}')
print(f' R-SQUARED3 {r2_score(y_train_dum_q, y_train_pred_4)}')

Resultados RIDGE(L2) -> intercepto: 20.7468330577957, coeficientes: [ 0.10900912 -0.25679913 -1.04950113  0.04447169  0.94858459  0.6194094
 -0.0875865  -0.37194117 -0.6194094  -0.14245656 -0.95495357 -1.15760936
  0.         -0.80850645  0.          0.        ]
 R-SQUARED3 0.994191969202774

In [68]:
ridge_predicho_qsec = ridge4.predict(X_escalado_test_dum_qsec)
r2_score(y_test_dum_q,ridge_predicho_qsec)

0.6769667364734808

# ANALISIS Y CONCLUSIONES DE TODOS LOS MODELOS:

COMPARACIÓN DE MPG EN 1.1 Y 2,1:
El fenomeno más notorio es el overfitting que sucede en las versiones con dummies, tienen puntajes perfectos que se representan en los Rsquared pero al intentar normalmente con las versiones de test los puntajes eran desastrozos, practicamente aleatorios; tenían mucho mejor desempeño conjunton por ejemplo Ridge sin dumies tenidno metricas muy aceptables. En general al hacer train slpit los etrenamiento tenían mucho ruido así que es dificil aceptar algún modelo pero definitivamente se comporto mejor la version tradicional; aunque talves los coeficientes pueden decirnos más en los dummies

COMPARACIÓN QSEC 1.1 Y2.1: El mismo caso, era igual de dificil decir que existe un over fitting sin hacer train-split, pero los valores en general con salida qsec era mucho mejores que lo que tenemos con mpg; tanto a´si que Ridge en dumies con qsec resulto una regresión aceptable (según mi codigo). Pero en general el fenomeno del overfitting (a excepción de qsec ridge) persistió. Indigando más en este ultima regresión experimente con alpha bajos y obtuve mejoras en ambos Rsquared test/train pero curiosamente solo aplicando penalisaciones bajas.